import type { Event } from '../types';

export const mockEvents: Event[] = [
  // İstanbul
  {
    id: '1',
    title: 'Sertab Erener Konseri',
    type: 'concert',
    city: 'İstanbul',
    date: '2026-04-15',
    time: '21:00',
    venue: 'Volkswagen Arena',
    description: 'Sertab Erener, en sevilen şarkılarını Volkswagen Arena\'da, İstanbul seyircisiyle buluşturuyor. Unutulmaz bir gece sizi bekliyor.',
    imageUrl: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?w=800',
    price: 2250,
    tags: ['pop', 'türk müziği'],
  },
  {
    id: '2',
    title: 'Hamlet — Devlet Tiyatrosu',
    type: 'theater',
    city: 'İstanbul',
    date: '2026-04-20',
    time: '19:30',
    venue: 'Atatürk Kültür Merkezi',
    description: 'Shakespeare\'in ölümsüz eseri Hamlet, Devlet Tiyatrosu\'nun güçlü kadrosuyla yeniden sahnede. Modern bir yorumla klasik bir trajedi.',
    imageUrl: 'https://images.unsplash.com/photo-1503095396549-807759245b35?w=800',
    price: 1000,
    tags: ['klasik', 'shakespeare'],
  },
  {
    id: '3',
    title: 'İstanbul Jazz Festivali',
    type: 'festival',
    city: 'İstanbul',
    date: '2026-05-10',
    time: '18:00',
    venue: 'Harbiye Açıkhava',
    description: 'Her yıl binlerce jazz severle buluşan İstanbul Jazz Festivali bu yıl uluslararası sanatçılarla kapılarını açıyor.',
    imageUrl: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
    price: 1750,
    tags: ['jazz', 'festival', 'uluslararası'],
  },
  {
    id: '4',
    title: 'Çağdaş Sanat Sergisi — ARTIM',
    type: 'exhibition',
    city: 'İstanbul',
    date: '2026-04-05',
    time: '10:00',
    venue: 'Istanbul Modern',
    description: 'ARTIM kolektifinden 15 sanatçının eserlerini barındıran bu sergi, çağdaş Türk sanatının nabzını tutmaya devam ediyor.',
    imageUrl: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800',
    isFree: true,
    tags: ['sergi', 'çağdaş sanat'],
  },
  {
    id: '5',
    title: 'Fenerbahçe - Galatasaray Derbisi',
    type: 'sports',
    city: 'İstanbul',
    date: '2026-04-27',
    time: '20:00',
    venue: 'Ülker Stadyumu',
    description: 'Türk futbolunun en büyük buluşması. Ülker Stadyumu\'nda unutulmaz derbi eşliğinde heyecan doruğa çıkıyor.',
    imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=800',
    price: 3000,
    tags: ['futbol', 'derbi', 'süper lig'],
  },
  {
    id: '6',
    title: 'Cem Yılmaz — Solo Stand-up',
    type: 'comedy',
    city: 'İstanbul',
    date: '2026-05-03',
    time: '21:00',
    venue: 'Zorlu PSM',
    description: 'Türkiye\'nin en sevilen komedyeni Cem Yılmaz, tamamen yeni materyaliyle sahnede. Gülerek ağlayacağınız bir gece!',
    imageUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800',
    price: 3750,
    tags: ['stand-up', 'komedi'],
  },

  // Ankara
  {
    id: '7',
    title: 'Ankara Senfoni Orkestrası Gala',
    type: 'concert',
    city: 'Ankara',
    date: '2026-04-18',
    time: '20:00',
    venue: 'Ankara CSO Konser Salonu',
    description: 'Cumhurbaşkanlığı Senfoni Orkestrası, Beethoven\'ın 9. Senfonisi ile müzik tutkunlarını buluşturuyor.',
    imageUrl: 'https://images.unsplash.com/photo-1464375117522-1311d6a5b81f?w=800',
    price: 1500,
    tags: ['klasik müzik', 'senfoni'],
  },
  {
    id: '8',
    title: 'Anadolu Medeniyetleri Özel Gece Turu',
    type: 'exhibition',
    city: 'Ankara',
    date: '2026-04-12',
    time: '19:00',
    venue: 'Anadolu Medeniyetleri Müzesi',
    description: 'Müzenin kapıları özel olarak açılıyor. Rehberli gece turunda Hitit, Friğ ve Roma dönemlerine ışık tutuluyor.',
    imageUrl: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=800',
    price: 750,
    tags: ['tarih', 'müze', 'kültür'],
  },
  {
    id: '9',
    title: "Tarkan Ankara'da",
    type: 'concert',
    city: 'Ankara',
    date: '2026-05-20',
    time: '21:30',
    venue: 'Congresium Ankara',
    description: 'Pop müziğin efsane ismi Tarkan, Başkent\'te muhteşem bir gece vaat ediyor. Onlarca hit şarkı, nefes kesici sahne gösterisi.',
    imageUrl: 'https://images.unsplash.com/photo-1567619741277-d35ba8d3b662?w=800',
    price: 2750,
    tags: ['pop', 'türk müziği'],
  },
  {
    id: '10',
    title: 'Ankara Tiyatro Festivali',
    type: 'festival',
    city: 'Ankara',
    date: '2026-04-25',
    time: '17:00',
    venue: 'Ankara Devlet Tiyatrosu',
    description: '10 günlük festival boyunca yerli ve yabancı toplulukların oyunlarını izleyebilir, atölyelerine katılabilirsiniz.',
    imageUrl: 'https://images.unsplash.com/photo-1508997449629-303059a039c0?w=800',
    price: 500,
    tags: ['tiyatro', 'festival'],
  },

  // İzmir
  {
    id: '11',
    title: 'İzmir International Music Festival',
    type: 'festival',
    city: 'İzmir',
    date: '2026-06-05',
    time: '18:00',
    venue: 'Atatürk Kültür Parkı',
    description: 'Dünyaca ünlü sanatçıların yer aldığı İzmir Uluslararası Müzik Festivali, şehrin en büyük yaz etkinliğine dönüştü.',
    imageUrl: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800',
    price: 1250,
    tags: ['festival', 'uluslararası', 'yaz'],
  },
  {
    id: '12',
    title: 'Eskiçağ İzmir Fotoğraf Sergisi',
    type: 'exhibition',
    city: 'İzmir',
    date: '2026-04-08',
    time: '09:00',
    venue: 'İzmir Arkeoloji Müzesi',
    description: 'Smyrna\'dan İzmir\'e uzanan tarihin fotoğraf kareleriyle anlatıldığı bu sergi, şehrin köklü geçmişini yansıtıyor.',
    imageUrl: 'https://images.unsplash.com/photo-1548092372-0d1bd40894a3?w=800',
    isFree: true,
    tags: ['fotoğraf', 'tarih', 'izmir'],
  },
  {
    id: '13',
    title: 'İzmir Büyükşehir Konseri',
    type: 'concert',
    city: 'İzmir',
    date: '2026-05-01',
    time: '20:00',
    venue: 'Konak Meydanı',
    description: 'İşçi Bayramı\'na özel İzmir Büyükşehir Belediyesi\'nin düzenlediği ücretsiz açıkhava konseri.',
    imageUrl: 'https://images.unsplash.com/photo-1501612780327-45045538702b?w=800',
    isFree: true,
    tags: ['açıkhava', 'ücretsiz'],
  },
  {
    id: '14',
    title: 'Altay - Altınordu Maçı',
    type: 'sports',
    city: 'İzmir',
    date: '2026-04-30',
    time: '19:00',
    venue: 'Alsancak Mustafa Denizli Stadyumu',
    description: 'İzmir derbisi Alsancak\'ta! Ege\'nin gururu iki takım birbirlerine rakip oluyor.',
    imageUrl: 'https://images.unsplash.com/photo-1518091043644-c1d4457512c6?w=800',
    price: 900,
    tags: ['futbol', 'izmir', 'derbi'],
  },

  // Bursa
  {
    id: '15',
    title: 'Bursa Uludağ Müzik Festivali',
    type: 'festival',
    city: 'Bursa',
    date: '2026-07-10',
    time: '16:00',
    venue: 'Uludağ Etkinlik Alanı',
    description: 'Uludağ\'ın eteklerinde müzik festivali! Doğa ve müziği birleştiren eşsiz bir deneyim yaşayın.',
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    price: 1500,
    tags: ['festival', 'doğa', 'yaz'],
  },
  {
    id: '16',
    title: 'Bursa Devlet Tiyatrosu: Kral Lear',
    type: 'theater',
    city: 'Bursa',
    date: '2026-04-22',
    time: '19:30',
    venue: 'Bursa Devlet Tiyatrosu',
    description: 'Shakespeare\'in güçlü trajedisi Kral Lear, Bursa Devlet Tiyatrosu\'nun deneyimli kadrosuyla sahneleniyor.',
    imageUrl: 'https://images.unsplash.com/photo-1516307365426-bea591f05011?w=800',
    price: 600,
    tags: ['tiyatro', 'shakespeare'],
  },

  // Antalya
  {
    id: '17',
    title: 'Antalya Film Forum',
    type: 'exhibition',
    city: 'Antalya',
    date: '2026-09-20',
    time: '10:00',
    venue: 'Antalya Kültür Merkezi',
    description: 'Türkiye\'nin en prestijli film festivali, endüstri profesyonellerini Antalya\'da buluşturuyor.',
    imageUrl: 'https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800',
    price: 1000,
    tags: ['film', 'festival', 'sinema'],
  },
  {
    id: '18',
    title: 'Duman Konseri — Antalya',
    type: 'concert',
    city: 'Antalya',
    date: '2026-05-17',
    time: '21:00',
    venue: 'Mark Antalya',
    description: 'Türk rock\'ının efsanesi Duman, Antalya\'ya geliyor. En iyi şarkıları ile müzik severleri bekliyor.',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800',
    price: 2000,
    tags: ['rock', 'türk rock'],
  },
  {
    id: '19',
    title: 'Akdeniz Spor Oyunları',
    type: 'sports',
    city: 'Antalya',
    date: '2026-06-15',
    time: '09:00',
    venue: 'Antalya Spor Kompleksi',
    description: 'Akdeniz ülkelerinin yarıştığı atletizm, yüzme ve diğer branşlarda heyecan verici müsabakalar.',
    imageUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=800',
    price: 400,
    tags: ['atletizm', 'uluslararası', 'spor'],
  },

  // Trabzon
  {
    id: '20',
    title: 'Trabzonspor — Beşiktaş',
    type: 'sports',
    city: 'Trabzon',
    date: '2026-05-04',
    time: '20:45',
    venue: 'Papara Park',
    description: 'Trabzon\'un gururu Trabzonspor, Beşiktaş\'ı ağırlıyor. Karadeniz fırtınası sahada!',
    imageUrl: 'https://images.unsplash.com/photo-1431324155629-1a6deb1dec8d?w=800',
    price: 1500,
    tags: ['futbol', 'süper lig'],
  },
  {
    id: '21',
    title: 'Karadeniz Halk Müziği Gecesi',
    type: 'concert',
    city: 'Trabzon',
    date: '2026-04-14',
    time: '19:00',
    venue: 'Trabzon Kültür Merkezi',
    description: "Karadeniz'in kendine özgü kemençe ve horon kültürünü yaşatacak büyük bir halk müziği gecesi.",
    imageUrl: 'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=800',
    price: 750,
    tags: ['halk müziği', 'karadeniz'],
  },

  // Konya
  {
    id: '22',
    title: 'Şeb-i Arus Törenleri',
    type: 'festival',
    city: 'Konya',
    date: '2026-12-17',
    time: '20:00',
    venue: 'Mevlânâ Kültür Merkezi',
    description: 'Hz. Mevlânâ\'nın vefatının yıl dönümünde düzenlenen Şeb-i Arus törenleri, dünyanın dört bir yanından ziyaretçi çekiyor.',
    imageUrl: 'https://images.unsplash.com/photo-1564769662533-4f00a87b4056?w=800',
    isFree: true,
    tags: ['kültür', 'mevlana', 'sema'],
  },
  {
    id: '23',
    title: 'Konya Gastronomi Festivali',
    type: 'festival',
    city: 'Konya',
    date: '2026-05-25',
    time: '11:00',
    venue: 'Konya Fuar Alanı',
    description: 'Türk ve dünya mutfağından lezzetlerin buluştuğu yemek festivali. Atölye çalışmaları ve canlı müzik eşliğinde.',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    price: 250,
    tags: ['gastronomi', 'yemek', 'festival'],
  },

  // Mersin
  {
    id: '24',
    title: 'Mersin Uluslararası Müzik Festivali',
    type: 'festival',
    city: 'Mersin',
    date: '2026-06-20',
    time: '19:00',
    venue: 'Mersin Açıkhava Tiyatrosu',
    description: 'Akdeniz sahilinde uluslararası müzisyenlerle dolu bir festival. Klasik ve çağdaş müziğin buluşma noktası.',
    imageUrl: 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?w=800',
    price: 1100,
    tags: ['festival', 'uluslararası'],
  },

  // Gaziantep
  {
    id: '25',
    title: 'Gaziantep Stand-Up Gecesi',
    type: 'comedy',
    city: 'Gaziantep',
    date: '2026-04-19',
    time: '21:00',
    venue: 'Rixos Hotel Gaziantep',
    description: 'Türkiye\'nin önde gelen stand-up sanatçıları Gaziantep\'te bir araya geliyor. Gülmekten karnınız ağrıyacak!',
    imageUrl: 'https://images.unsplash.com/photo-1499364615650-ec38552f4f34?w=800',
    price: 1400,
    tags: ['stand-up', 'komedi'],
  },
  {
    id: '26',
    title: 'Zeugma Mozaik Müzesi Gece Turu',
    type: 'exhibition',
    city: 'Gaziantep',
    date: '2026-04-10',
    time: '20:00',
    venue: 'Zeugma Mozaik Müzesi',
    description: 'Dünyanın en büyük mozaik müzesi özel gece turlarına açılıyor. Rehber eşliğinde tarihin derinliklerine inin.',
    imageUrl: 'https://images.unsplash.com/photo-1569872255200-1fc4bafcc65c?w=800',
    price: 500,
    tags: ['müze', 'tarih', 'kültür'],
  },

  // Adana
  {
    id: '27',
    title: 'Sıla Konseri — Adana',
    type: 'concert',
    city: 'Adana',
    date: '2026-05-30',
    time: '21:00',
    venue: 'Adana Büyükşehir Belediyesi Amfi',
    description: 'Pop müziğin güçlü sesi Sıla, Adana\'da müzik severlerle buluşuyor. Açıkhava konser şöleni.',
    imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800',
    price: 1900,
    tags: ['pop', 'açıkhava'],
  },
  {
    id: '28',
    title: 'Adana Tiyatro Festivali',
    type: 'festival',
    city: 'Adana',
    date: '2026-05-12',
    time: '18:00',
    venue: 'Adana Sabancı Kültür Merkezi',
    description: '5 günlük tiyatro festivali boyunca Türkiye\'nin en iyi sahneden sanat toplulukları perdelerini açıyor.',
    imageUrl: 'https://images.unsplash.com/photo-1560169897-fc0cdbdfa4d5?w=800',
    price: 450,
    tags: ['tiyatro', 'festival'],
  },

  // İstanbul — ek etkinlikler
  {
    id: '29',
    title: 'Manga Konseri',
    type: 'concert',
    city: 'İstanbul',
    date: '2026-05-09',
    time: '21:30',
    venue: 'Hayal Kahvesi',
    description: 'Türk rock\'ına yeni soluk katan Manga, Hayal Kahvesi sahnesinde akustik bir gece sunuyor.',
    imageUrl: 'https://images.unsplash.com/photo-1429962714451-bb934ecdc4ec?w=800',
    price: 1750,
    tags: ['rock', 'akustik'],
  },
  {
    id: '30',
    title: 'İstanbul Maratonu 2026',
    type: 'sports',
    city: 'İstanbul',
    date: '2026-11-01',
    time: '08:00',
    venue: 'Asya ve Avrupa yakası arası',
    description: 'Dünyanın iki kıtaya yayılan tek maratonu! İstanbul Boğazı üzerinden koşarak tarihi bir deneyim yaşayın.',
    imageUrl: 'https://images.unsplash.com/photo-1542281286-9e0a16bb7366?w=800',
    price: 600,
    tags: ['maraton', 'koşu', 'spor'],
  },
];
